#Assumes Node.js React Frontend, Express.js API server, & PostgreSQL Database

version: '3.8'

services:
  frontend:
  # GUI
    build: frontend/
    container_name: 'frontend'
    depends_on:
      - 'database'
    environment:
      - VITE_PORT=${VITE_PORT}
    ports:
      - '5173:5173'
      # 5173 is the default Node.js server, change if ports have been changed to something like 8080
  api:
    # Backend Express Server
    build: api/
    container_name: 'backend'
    depends_on:
      - 'database'
    environment:
      - EXPRESS_PORT=${EXPRESS_PORT}
    ports:
      - '3000:3000'
      # 3000 is default Express.js port, again - change if application has something different
  database:
    image: postgres:latest
    container_name: postgres-database
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # Any environment variables from within the .env file (this file is in the .gitignore, must be made locally with variables matching)
    ports:
      - '5432:5432'
      # Default Postgres Port, change is required
    volume:
      - $HOME/docker
